#!/usr/bin/env bash
# ============================================
# apply-theme.sh — Distribute colors.json to all consumers
# ============================================
# Reads ~/.config/theme/colors.json and generates themed configs for:
#   Hyprland, Kitty, Neovim, Starship, Hyprlock, Zathura
#
# Usage: apply-theme.sh [--no-reload]

set -euo pipefail

THEME_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/theme"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
COLORS_FILE="$THEME_DIR/colors.json"

[[ -f "$COLORS_FILE" ]] || { echo "Missing $COLORS_FILE" >&2; exit 1; }
command -v jq &>/dev/null || { echo "jq is required" >&2; exit 1; }

NO_RELOAD=false
KITTY_ONLY=false
for arg in "$@"; do
    case "$arg" in
        --no-reload)  NO_RELOAD=true ;;
        --kitty-only) KITTY_ONLY=true ;;
    esac
done

# ── Helpers ────────────────────────────────────────────────

# Read color as hex without # (e.g., "cba6f7")
c() { jq -r ".[\"$1\"] // empty" "$COLORS_FILE" | tr -d '#' | tr '[:upper:]' '[:lower:]'; }

# Read color with # prefix (e.g., "#cba6f7")
ch() { jq -r ".[\"$1\"] // empty" "$COLORS_FILE"; }

# Read color uppercase without # (e.g., "CBA6F7")
cu() { jq -r ".[\"$1\"] // empty" "$COLORS_FILE" | tr -d '#' | tr '[:lower:]' '[:upper:]'; }

# ── Catppuccin palette generation (shared by nvim + starship) ────
#
# catppuccin26.py takes a seed color and hue-rotates the entire Catppuccin
# Mocha palette in CIELAB LCH space — same perceptually uniform approach
# as dank16.py for ANSI terminal colors.  Every accent gets its own
# distinct hue; surfaces get a subtle tint from the seed.

PALETTE_KEYS=(rosewater flamingo pink mauve red maroon peach yellow green teal sky sapphire blue lavender text subtext1 subtext0 overlay2 overlay1 overlay0 surface2 surface1 surface0 base mantle crust)

# Generate palette JSON from source_color (or default to Catppuccin Mocha)
_palette_json=""
_generate_palette() {
    local source_color
    source_color=$(jq -r '.source_color // empty' "$COLORS_FILE")
    if [[ -n "$source_color" ]]; then
        _palette_json=$(python3 "$THEME_DIR/catppuccin26.py" "$source_color")
    else
        # Static mode — identity (original Catppuccin Mocha)
        _palette_json=$(python3 "$THEME_DIR/catppuccin26.py")
    fi
}

# Read a generated palette color
pc() { echo "$_palette_json" | jq -r ".[\"$1\"] // empty"; }

# Emit palette lines in lua or toml format
palette_lines() {
    local fmt="${1:-toml}"
    for key in "${PALETTE_KEYS[@]}"; do
        local value
        value="$(pc "$key")"
        case "$fmt" in
            lua)  printf '  %-9s = "%s",\n' "$key" "$value" ;;
            toml) printf '%s = "%s"\n' "$key" "$value" ;;
        esac
    done
}

# Convert hex to rgba(r,g,b,a) for zathura
hex_to_rgba() {
    local hex
    hex="$(echo "$1" | tr -d '#')"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "rgba($r,$g,$b,${2:-1})"
}

# ── Hyprland generated.conf ───────────────────────────────

generate_hyprland() {
    local out="$CONFIG_DIR/hypr/themes/generated.conf"
    mkdir -p "$(dirname "$out")"

    cat > "$out" << EOF
# Auto-generated by apply-theme.sh — DO NOT EDIT
# Material You color variables for Hyprland

\$primary = rgb($(c primary))
\$primaryAlpha = $(c primary)
\$onPrimary = rgb($(c on_primary))
\$onPrimaryAlpha = $(c on_primary)

\$secondary = rgb($(c secondary))
\$secondaryAlpha = $(c secondary)
\$onSecondary = rgb($(c on_secondary))

\$tertiary = rgb($(c tertiary))
\$tertiaryAlpha = $(c tertiary)

\$error = rgb($(c error))
\$errorAlpha = $(c error)

\$surface = rgb($(c surface))
\$surfaceAlpha = $(c surface)
\$onSurface = rgb($(c on_surface))
\$onSurfaceAlpha = $(c on_surface)
\$onSurfaceVariant = rgb($(c on_surface_variant))
\$surfaceDim = rgb($(c surface_dim))
\$surfaceDimAlpha = $(c surface_dim)

\$surfaceContainer = rgb($(c surface_container))
\$surfaceContainerAlpha = $(c surface_container)
\$surfaceContainerHigh = rgb($(c surface_container_high))
\$surfaceContainerHighAlpha = $(c surface_container_high)
\$surfaceContainerHighest = rgb($(c surface_container_highest))
\$surfaceContainerLowest = rgb($(c surface_container_lowest))
\$surfaceContainerLowestAlpha = $(c surface_container_lowest)

\$outline = rgb($(c outline))
\$outlineVariant = rgb($(c outline_variant))

\$inverseSurface = rgb($(c inverse_surface))
\$inversePrimary = rgb($(c inverse_primary))

\$success = rgb($(c success))
\$warning = rgb($(c warning))
\$caution = rgb($(c caution))

# Pre-computed rgba for shadow (Hyprland can't interpolate vars in strings)
\$shadowColor = rgba($(c surface_container_lowest)aa)
\$shadowColorInactive = rgba($(c surface)aa)
EOF

    if [[ "$NO_RELOAD" == false ]]; then
        hyprctl reload &>/dev/null || true
    fi
}

# ── Kitty current-theme.conf ──────────────────────────────

generate_kitty() {
    local out="$CONFIG_DIR/kitty/current-theme.conf"
    mkdir -p "$(dirname "$out")"

    # Determine ANSI terminal colors (indices 0–15)
    # Dynamic mode: derive vibrant 16-color palette from wallpaper seed via dank16.py
    # Static mode:  use exact hardcoded Catppuccin Mocha ANSI values
    local SOURCE_COLOR
    SOURCE_COLOR=$(jq -r '.source_color // empty' "$COLORS_FILE")

    local -a ANSI_COLORS
    if [[ -n "$SOURCE_COLOR" ]]; then
        mapfile -t ANSI_COLORS < <(
            python3 "$THEME_DIR/dank16.py" "$SOURCE_COLOR" \
                | jq -r '.ansi[] | ltrimstr("#") | ascii_upcase'
        )
    else
        # Catppuccin Mocha exact ANSI values (order: 0–7, then 8–15)
        ANSI_COLORS=(
            "45475A" "F38BA8" "A6E3A1" "F9E2AF" "89B4FA" "CBA6F7" "94E2D5" "BAC2DE"
            "585B70" "F38BA8" "A6E3A1" "F9E2AF" "89B4FA" "CBA6F7" "94E2D5" "CDD6F4"
        )
    fi

    cat > "$out" << EOF
# vim:ft=kitty
# Auto-generated by apply-theme.sh — DO NOT EDIT

# The basic colors
foreground              #$(cu on_surface)
background              #$(cu surface)
selection_foreground    #$(cu surface)
selection_background    #$(cu primary)

# Cursor colors
cursor                  #$(cu primary)
cursor_text_color       #$(cu surface)

# URL underline color when hovering with mouse
url_color               #$(cu primary)

# Kitty window border colors
active_border_color     #$(cu secondary)
inactive_border_color   #$(cu outline)
bell_border_color       #$(cu warning)

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #$(cu on_primary)
active_tab_background   #$(cu primary)
inactive_tab_foreground #$(cu on_surface)
inactive_tab_background #$(cu surface_dim)
tab_bar_background      #$(cu surface_container_lowest)

# Colors for marks (marked text in the terminal)
mark1_foreground #$(cu surface)
mark1_background #$(cu secondary)
mark2_foreground #$(cu surface)
mark2_background #$(cu primary)
mark3_foreground #$(cu surface)
mark3_background #$(cu tertiary)

# The 16 terminal colors

# black
color0  #${ANSI_COLORS[0]}
color8  #${ANSI_COLORS[8]}

# red
color1  #${ANSI_COLORS[1]}
color9  #${ANSI_COLORS[9]}

# green
color2  #${ANSI_COLORS[2]}
color10 #${ANSI_COLORS[10]}

# yellow
color3  #${ANSI_COLORS[3]}
color11 #${ANSI_COLORS[11]}

# blue
color4  #${ANSI_COLORS[4]}
color12 #${ANSI_COLORS[12]}

# magenta
color5  #${ANSI_COLORS[5]}
color13 #${ANSI_COLORS[13]}

# cyan
color6  #${ANSI_COLORS[6]}
color14 #${ANSI_COLORS[14]}

# white
color7  #${ANSI_COLORS[7]}
color15 #${ANSI_COLORS[15]}
EOF

    if [[ "$NO_RELOAD" == false ]]; then
        # Send SIGUSR1 to kitty for live reload
        pkill -USR1 kitty &>/dev/null || true
    fi
}

# ── Neovim palette ────────────────────────────────────────

generate_nvim() {
    local out="$THEME_DIR/nvim-palette.lua"

    {
        echo '-- Auto-generated by apply-theme.sh — DO NOT EDIT'
        echo '-- Maps Material You colors back to Catppuccin names for catppuccin/nvim'
        echo 'return {'
        palette_lines lua
        echo '}'
    } > "$out"

    if [[ "$NO_RELOAD" == false ]]; then
        # Send SIGUSR1 to Neovim instances for live reload
        pkill -USR1 nvim &>/dev/null || true
    fi
}

# ── Starship palette ──────────────────────────────────────

generate_starship() {
    local conf="$CONFIG_DIR/starship.toml"
    [[ -f "$conf" ]] || return 0

    # Replace the [palettes.catppuccin_mocha] section in-place
    local tmp
    tmp="$(mktemp)"

    # Write everything up to and including [palettes.catppuccin_mocha]
    awk 'BEGIN{f=0} /^\[palettes\.catppuccin_mocha\]/{print;f=1;next} f&&/^\[/{f=0} f==0{print}' "$conf" > "$tmp"

    # Append the new palette values
    palette_lines toml >> "$tmp"

    cat "$tmp" > "$conf"
    rm -f "$tmp"
}

# ── Hyprlock colors ───────────────────────────────────────

generate_hyprlock() {
    local out="$CONFIG_DIR/hypr/themes/hyprlock-colors.conf"
    mkdir -p "$(dirname "$out")"

    cat > "$out" << EOF
# Auto-generated by apply-theme.sh — DO NOT EDIT
# Material You colors for Hyprlock

# Raw hex values (for rgb() usage)
\$lockPrimary = $(c primary)
\$lockOnPrimary = $(c on_primary)
\$lockSurface = $(c surface)
\$lockOnSurface = $(c on_surface)
\$lockError = $(c error)
\$lockSuccess = $(c success)
\$lockTertiary = $(c tertiary)
\$lockCaution = $(c caution)
\$lockOnSurfaceVariant = $(c on_surface_variant)

# Pre-computed rgba (Hyprland can't interpolate \${var} in strings)
\$lockPrimaryRing = rgba($(c primary)ee)
\$lockSurfaceInner = rgba($(c surface)80)
\$lockTertiaryText = rgba($(c tertiary)cc)
\$lockPrimaryText = rgba($(c primary)ff)
\$lockOnSurfaceText = rgba($(c on_surface)b3)
\$lockCautionText = rgba($(c caution)80)
EOF
}

# ── Zathura colors ────────────────────────────────────────

generate_zathura() {
    local out="$CONFIG_DIR/zathura/catppuccin-mocha"
    mkdir -p "$(dirname "$out")"

    local on_surface on_surface_variant surface surface_container
    local surface_dim surface_container_lowest primary error warning outline
    on_surface="$(ch on_surface)"
    on_surface_variant="$(ch on_surface_variant)"
    surface="$(ch surface)"
    surface_container="$(ch surface_container)"
    surface_dim="$(ch surface_dim)"
    surface_container_lowest="$(ch surface_container_lowest)"
    primary="$(ch primary)"
    error="$(ch error)"
    warning="$(ch warning)"
    outline="$(ch outline)"

    cat > "$out" << EOF
set default-fg                $(hex_to_rgba "$on_surface")
set default-bg                $(hex_to_rgba "$surface")

set completion-bg             $(hex_to_rgba "$surface_container")
set completion-fg             $(hex_to_rgba "$on_surface")
set completion-highlight-bg   $(hex_to_rgba "$primary")
set completion-highlight-fg   $(hex_to_rgba "$surface")
set completion-group-bg       $(hex_to_rgba "$surface_dim")
set completion-group-fg       $(hex_to_rgba "$on_surface")

set statusbar-fg              $(hex_to_rgba "$on_surface")
set statusbar-bg              $(hex_to_rgba "$surface_container_lowest")
set inputbar-fg               $(hex_to_rgba "$on_surface")
set inputbar-bg               $(hex_to_rgba "$surface")

set notification-bg           $(hex_to_rgba "$surface")
set notification-fg           $(hex_to_rgba "$on_surface")
set notification-error-bg     $(hex_to_rgba "$surface")
set notification-error-fg     $(hex_to_rgba "$error")
set notification-warning-bg   $(hex_to_rgba "$surface")
set notification-warning-fg   $(hex_to_rgba "$warning")

set recolor                   "true"
set recolor-lightcolor        $(hex_to_rgba "$surface")
set recolor-darkcolor         $(hex_to_rgba "$on_surface")

set index-fg                  $(hex_to_rgba "$on_surface")
set index-bg                  $(hex_to_rgba "$surface")
set index-active-fg           $(hex_to_rgba "$on_surface")
set index-active-bg           $(hex_to_rgba "$surface_container")

set render-loading-bg         $(hex_to_rgba "$surface")
set render-loading-fg         $(hex_to_rgba "$on_surface")

set highlight-color           $(hex_to_rgba "$outline" 0.3)
set highlight-fg              $(hex_to_rgba "$on_surface")
set highlight-active-color    $(hex_to_rgba "$primary" 0.3)
EOF
}

# ── GTK 3/4 colors.css ────────────────────────────────────

generate_gtk() {
    for ver in 3.0 4.0; do
        local out="$CONFIG_DIR/gtk-$ver/colors.css"
        mkdir -p "$(dirname "$out")"
        cat > "$out" << EOF
/* Auto-generated by apply-theme.sh — DO NOT EDIT */
@define-color accent_bg_color $(ch primary);
@define-color accent_fg_color $(ch on_primary);
@define-color accent_color $(ch primary);
@define-color window_bg_color $(ch surface);
@define-color window_fg_color $(ch on_surface);
@define-color view_bg_color $(ch surface_dim);
@define-color view_fg_color $(ch on_surface);
@define-color headerbar_bg_color $(ch surface);
@define-color headerbar_fg_color $(ch on_surface);
@define-color card_bg_color $(ch surface_container);
@define-color card_fg_color $(ch on_surface);
@define-color popover_bg_color $(ch surface_container);
@define-color popover_fg_color $(ch on_surface);
@define-color sidebar_bg_color $(ch surface_dim);
@define-color sidebar_fg_color $(ch on_surface);
@define-color dialog_bg_color $(ch surface_container);
@define-color dialog_fg_color $(ch on_surface);
@define-color destructive_bg_color $(ch error);
@define-color destructive_fg_color $(ch on_error);
@define-color success_bg_color $(ch success);
@define-color success_fg_color $(ch on_success);
@define-color warning_bg_color $(ch warning);
@define-color warning_fg_color $(ch on_warning);
@define-color error_bg_color $(ch error);
@define-color error_fg_color $(ch on_error);
EOF

        if [[ "$ver" == 4.0 ]]; then
            cat >> "$out" << EOF

:root {
  --accent-bg-color: $(ch primary);
  --accent-fg-color: $(ch on_primary);
  --window-bg-color: $(ch surface);
  --window-fg-color: $(ch on_surface);
  --view-bg-color: $(ch surface_dim);
  --view-fg-color: $(ch on_surface);
  --headerbar-bg-color: $(ch surface);
  --headerbar-fg-color: $(ch on_surface);
  --card-bg-color: $(ch surface_container);
  --card-fg-color: $(ch on_surface);
  --popover-bg-color: $(ch surface_container);
  --popover-fg-color: $(ch on_surface);
  --sidebar-bg-color: $(ch surface_dim);
  --sidebar-fg-color: $(ch on_surface);
  --dialog-bg-color: $(ch surface_container);
  --dialog-fg-color: $(ch on_surface);
  --destructive-bg-color: $(ch error);
  --destructive-fg-color: $(ch on_error);
  --success-bg-color: $(ch success);
  --success-fg-color: $(ch on_success);
  --warning-bg-color: $(ch warning);
  --warning-fg-color: $(ch on_warning);
  --error-bg-color: $(ch error);
  --error-fg-color: $(ch on_error);
}
EOF
        fi
    done
}

# ── Main ──────────────────────────────────────────────────

if [[ "$KITTY_ONLY" == true ]]; then
    generate_kitty
    exit 0
fi

echo "Applying theme from $COLORS_FILE..."

_generate_palette

generate_hyprland
generate_kitty
generate_nvim
generate_starship
generate_hyprlock
generate_zathura
generate_gtk

echo "Theme applied to all consumers."
